# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
    - 3.6

# test minium required and latest versions of SciPy and NumPy
env:
    - version=latest

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

install:
    - if [[ $version == latest ]]; then conda create -q -n test_env python=$TRAVIS_PYTHON_VERSION numpy scipy six pandas matplotlib dill nose statsmodels scikit-learn; fi
    - source activate test_env
    - pip install lmfit
    - conda install -c conda-forge pyopencl
    - python setup.py install
    - conda list

script:
    - cd tests
    - nosetests
    
notifications:
  email: false
